version: '3.1'
services:

  application:
    build: .
    container_name: demo_api
    restart: always
    volumes:
      - ./:/var/www
    links:
      - mysql:mysql
    ports:
      - "8080:80"
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: demo_api_mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lumen_api
      MYSQL_ROOT_PASSWORD: 